---
- name: vault-tls | Create CA private key
  community.crypto.openssl_privatekey:
    path: "{{ vault_dir_tls }}/ca.key"
    cipher: auto
    size: 2048
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0600'
  register: vault_tls_cakey
  when: inventory_hostname == vault_master

- name: vault-tls | Create CA csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ vault_dir_tls }}/ca.key"
    common_name: "{{ vault_conf_cluster_name }} ca"
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: vault_ca_req
  when:
    - inventory_hostname == vault_master
    - vault_tls_cakey is changed

- name: vault-tls | Create CA certificate
  community.crypto.x509_certificate:
    path: "{{ vault_dir_tls }}/ca.crt"
    csr_content: "{{ vault_ca_req.csr }}"
    privatekey_path: "{{ vault_dir_tls }}/ca.key"
    selfsigned_not_after: "+730d"
    provider: selfsigned
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0644'
  when:
    - inventory_hostname == vault_master
    - vault_ca_req is changed

- name: vault-tls | Slurp CA certificate
  ansible.builtin.slurp:
    src: "{{ vault_dir_tls }}/{{ item }}"
  register: vault_tls_caslurp
  when: inventory_hostname == vault_master
  loop:
    - "ca.key"
    - "ca.crt"
  no_log: true

- name: vault-tls | Add CA certificates to nodes
  ansible.builtin.copy:
    dest: "{{ vault_dir_tls }}/{% if 'PRIVATE KEY' in (item.content | b64decode) %}ca.key{% else %}ca.crt{% endif %}"
    content: "{{ item.content | b64decode }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{% if 'PRIVATE KEY' in (item.content | b64decode) %}0600{% else %}0644{% endif %}"
  when:
    - inventory_hostname != vault_master
    - hostvars[vault_master]['vault_tls_cakey']['changed']
  loop: "{{ hostvars[vault_master]['vault_tls_caslurp']['results'] }}"
  no_log: true

- name: vault-tls | Create vault private key
  community.crypto.openssl_privatekey:
    path: "{{ vault_dir_tls }}/vault.key"
    size: 2048
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0600'
  register: vault_tls_key

- name: vault-tls | Create vault csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ vault_dir_tls }}/vault.key"
    common_name: "{{ vault_conf_cluster_name }}"
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:localhost"
      - "IP:{{ ansible_default_ipv4.address }}"
      - "IP:127.0.0.1"
  register: vault_req
  when: vault_tls_key is changed

- name: vault-tls | Generate vault certificate
  community.crypto.x509_certificate:
    path: "{{ vault_dir_tls }}/vault.crt"
    csr_content: "{{ vault_req.csr }}"
    ownca_path: "{{ vault_dir_tls }}/ca.crt"
    ownca_privatekey_path: "{{ vault_dir_tls }}/ca.key"
    ownca_not_after: "+730d"
    provider: ownca
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0644'
  when: vault_req is changed

- name: vault-tls | Create directory for vault CA certificate
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/VAULT
    state: directory
    mode: '0755'

- name: vault-tls | Create link to vault CA certificate
  ansible.builtin.file:
    src: "{{ vault_dir_tls }}/ca.crt"
    dest: "/usr/local/share/ca-certificates/VAULT/vault-ca.crt"
    state: link
  register: vault_ca_link

- name: vault-tls | Update CA certificates
  ansible.builtin.command: /usr/sbin/update-ca-certificates --fresh
  when: vault_ca_link is changed
