---
- name: vault-configure | Create vault config
  ansible.builtin.template:
    src: "config.hcl.j2"
    dest: "{{ vault_dir.conf }}/config.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0644'
  register: vault_config

- name: vault-configure | Create vault service
  ansible.builtin.template:
    src: "vault.service.j2"
    dest: "/etc/systemd/system/vault.service"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0644'
  register: vault_service

- name: vault-configure | Retart vault
  ansible.builtin.service:
    name: vault
    state: restarted
    enabled: true
  when: vault_config is changed or
        vault_service is changed
