---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: converge | Deploy vault single
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
